### ISSUE TITLE
Rename npm package to @typedigital/eslint-config

### ISSUE THREAD

**Issue by timidak** [typedigital/eslint-config-typedigital#16]
**The orga-scoped name looks much cleaner to me and everything works just fine now with it.**

### Possible Problems
* other developers need to switch from the old dependency to the new one to get updates
* unsure about how seemingless the migration will be

**Comment by timidak** [comment]
@JoeTypeDigital what do you think? is it worth to try it? It would be also the second package of our orga "typedigital" on `npm`.

**Comment by JoeTypeDigital** [comment]
I think we should do it now since I think that will happen eventually anyway. I think the pros far outweigh the cons here. If other devs are a concern, afaik you can get npm to print a console log informing them about the orga change fyi. Something like: this version will be discontinued, upgrade to xyz to keep up. babel did something similar.

**Comment by timidak** [comment]
Alright, I'll remove the question label. Maybe the feature will make it into the next release. 💯 
Yes, it's possible to deprecate a package via `npm deprecate <package>` and to add a message to the command.
