### ISSUE TITLE
[Feature] use unary + instead of parseInt or Number()

### ISSUE THREAD

**Issue by JoeTypeDigital** [typedigital/eslint-config-typedigital#71]
**Is there something missing in our code style? Please describe.**

unary + operator gets flagged as an error and it is recommended to use e.g. Number(value) instead of (+value)

**Describe how the feature should be implemented to fit your needs.**

It should be regarded as best practice to use the unary +, because it can be used on all numerical types (e.g. float, int) and implicitly converts them.

**Additional context**

![image](https://user-images.githubusercontent.com/37806384/152839062-8fbeddcf-1756-4eb2-82cd-40f3292fb710.png)
this is the error: it should be fixed.

**Comment by bob606** [comment]
As you can see here https://dev.to/sanchithasr/7-ways-to-convert-a-string-to-number-in-javascript-4l `Number()` can also be used on all numerical types and it has a higher readability.  I would not adjust the `no-implicit-coercion' rule. Please close the issue, if you are of the same opinion @JoeTypeDigital .

**Comment by bob606** [comment]
> Your source doesn't provide anything except showing that yes, just as eslint recommends Number(x) can be infact used to do convert strings to numbers. First of all: I regard the better readability as highly subjective. I personally (and I know @timidak feels the same way) find that `Nmber(x)` strictly bloats code and does little else. Additionally, I find little reason except bias not to use the unary + which at least should not throw an error. If you still feel strongly about closing this issue please contact @timidak to arbitrate whether this should be fixed or not.

I used the source as in the issue it was stated the reason to use unary instead of number was that it can convert all types.

>  because it can be used on all numerical types (e.g. float, int) and implicitly converts them.
I simply stated that Number can also do that in thus the reason provided is not sufficient. 

If the reason for adapting this rule is code bloating, then this is a different story. 7 (`Number()`) to 1(`+`) character for sure seems like a reasonable argument for this. Should we maybe also find a rule which disallows `Number()` conversions to have a standardized code style. I am sure for beginners at least for me as a beginner it's harder to read, but in fact it's easy to adapt to it, like you said.

**Comment by JoeTypeDigital** [comment]
I think a suitable solution is to disable the rule creating an error. If there is such a rule we can discourage the use but I'm afraid there might not be a rule for this.

**Comment by timidak** [comment]
> I think a suitable solution is to disable the rule creating an error. If there is such a rule we can discourage the use but I'm afraid there might not be a rule for this.

The rule we're talking about is `no-implicit-coercion`, right?
I'm okay with using the unary, but I'm a senior developer and I know what it does in this context. Imho junior devs could have problems to "parse" what the unary is doing, so this could lead to errors.

Also if we turn this off this operation `"" + 5643` will produce a string `"5643"`.  This is also very hard to understand for developers new to JavaScript & TS.

So, maybe we leave it as it is? What do you think @JoeTypeDigital @bob606?

@JoeTypeDigital if you're ok with leaving you can close the issue, otherwise we can discuss this further! 👍🏼
