### ISSUE TITLE
Should we use semicolons again?

### ISSUE THREAD

**Issue by timidak** [typedigital/eslint-config-typedigital#8]
### Questions:
- is it better for the TS compiler?
- is it easier to understand and write for junior coders?
- what benefits do we have using / not using semicolons?

**Comment by timidak** [comment]
What do you think @JoeTypeDigital @wunderjo and which one is your account? 😄

**Comment by timidak** [comment]
*friendly ping* @JoeTypeDigital

**Comment by JoeTypeDigital** [comment]
I don't know whether or not it is better for the TS Compiler, tbh. 
I think it has benefits for Juniors as well since using semicolons is more in line with most programming languages esp. ones people tend to lern first, e.g. C, JAVA.
When it comes to us, i think we have the huge benefit of me really liking them, opposed by the fact that our entire app is without them at this point in time.

**Comment by timidak** [comment]
Alright. Than I would say we add them again. In the next version as warning and in the next major version as error, to migrate more smoothly. 😁
